part1: p1.cpp 
	g++ p1.cpp easycurses.cpp -l ncurses -o p1
part2: 

part3: 
	
part4: 

part5: 

################## DON'T TOUCH BELOW ##################
run1: part1
	@./part1
run_%: %
	@test -f $* && echo "$*: Code compiled successfully" 

